### ISSUE TITLE
Read/Write towards Redis & flash wear investigation

### ISSUE THREAD

**Issue by volvorenjithraj** [w3c/automotive-viss2#105]
Hey, Just wondering if any investigation carried out around topic of Flash wear for REDIS read/write operation while it is being deployed to target Vehicle hw.
Since VISS involves read/write of  high frequency VSS datapoints, Flash wear will be a major concern ?

**Comment by UlfBj** [comment]
@volvorenjithraj my understanding is that Redis typically runs in RAM, not Flash?

**Comment by volvorenjithraj** [comment]
@UlfBj Yeah , I see both support for Redis, DRAM & Flash as well.Wondering if historical data point storage leverage flash as well ?

**Comment by jrask** [comment]
Following this since I am very curious about this.

**Comment by UlfBj** [comment]
The historical data point storage runs in RAM. It does not use Redis for its storage needs.

**Comment by renjithrajagopal-sudo** [comment]
@UlfBj  Thank you for update.
