### ISSUE TITLE
.gitignore excludes server/vissv2server/ path from git rep

### ISSUE THREAD

**Issue by slawr** [w3c/automotive-viss2#107]
### Summary
Trying to add source from server/vissv2server/ causes git to fail due to the .gitignore. 

Example:
```
automotive-viss2$ git add server/vissv2server/vissv2server.go 
The following paths are ignored by one of your .gitignore files:
server/vissv2server
Use -f if you really want to add them.

```

### Detail
At first quick look at the .gitignore I can't determine which pattern is causing the path to be ignored. The path could be added to the list of paths to not be included in pattern matching but it would seem to be more correct to fix the pattern itself?

### Workaround
Obvious one of using -f in git add to override ignore.

**Comment by UlfBj** [comment]
PR#109 hopefully fixes it.

**Comment by UlfBj** [comment]
As I have not heard any new complaints of the sort I conclude the fix is working.
Thus closing this.
