### ISSUE TITLE
Need for a simple tutorial?

### ISSUE THREAD

**Issue by erikbosch** [w3c/automotive-viss2#57]
This is one of few (if not the only) reference implementation(s) for VISS v2. I was thinking if would make sense to create a simple tutorial on how to start server and client and how to use them to for example read or subscribe to `Vehicle.Speed`.  That could help understanding the implementation, including what you must do to "feed" speed values to the server. I am thinking of steps like:

1. Configure a "dummy speed feeder" that updates speed every second
2. Start the server
3. Start the client, subscribe to `Vehicle.Speed` and make sure that you get a new speed value every second

That could also help if someone wants to implement "their own" server or client, then they can just replace the reference server/client with their own implementation and use the reference client or server for interaction.

**Comment by UlfBj** [comment]
A good idea. I take it on to create one.

**Comment by petervolvowinz** [comment]
Good idea!

**Comment by erikbosch** [comment]
In addition to `Vehicle.Speed` as a sensor example, one could think of also having a tutorial for an actuator in the same way, like `Vehicle.Body.Hood.Position`. I.e. showing how you can let a "dummy hood actuator" connect to the server and listen to requests and report position, so that you in the client can do a set request, and then by get-requests observe how the hood slowly moves to the wanted position

**Comment by petervolvowinz** [comment]
Yes. I like I, we could use/extend the Feeder "simulation" as the basis for the south-bound interface where we "place " a dummy actuator. I am currently working on the feeder integration towards remotiveLabs broker and was thinking of cleaning up the simulation part anyway, not just uncomment. So, I can take a look at your idea while doing that.

**Comment by petervolvowinz** [comment]
For Vehicle.Speed we could probably loop thru some values from a recorded data set I have. Then it will be from an actual vehicle.

**Comment by UlfBj** [comment]
There is now a tutorial skeleton in the /tutorial directory. HUGO is used to render the markdown content, which is auto updated into https://w3c.github.io/automotive-viss2/ when content is merged.

**Comment by UlfBj** [comment]
Fixed in PRs #62 - #65
