### ISSUE TITLE
[AAOS-VISS]Subscription updates doesn't work as expected with Path filters

### ISSUE THREAD

**Issue by volvorenjithraj** [w3c/automotive-viss2#68]
Description:
AAOS-VHAL/gRPC client app leverage Subscribe API with path Filter option(https://www.w3.org/TR/viss2-core/#filter-request) for 
receiving multiple VSS leaf nodes updates

Steps to Reproduce:
Checkout branch rl-integration. In this branch feeder uses dataprovider as remotivelabs broker interface towards virtual cloud
1.Launch docker using docker-compose up -d
2.Launch grpc client & try to Subscribe for attribute `commandList[1] = `{"action":"subscribe","path":"Vehicle","filter":{"type":"paths","parameter":["VehicleIdentification.VIN", "VehicleIdentification.Model","Speed"]},"requestId":"246"}``
3. Start remotivelabs virtual data playback 

Expected Behavior:
1.Docker shall launch vissv2server, feeder & redis running
2.AAOS/VHAL or Grpc client shall receive successful response
3.AAOS/VHAL or Grpc client shall receive successful event for Speed, VIN & Model when it is available

Actual Behavior:
1.OK
2.OK
3.VISSv2 server not notifying neither speed/vin/model back to client even though feeder has all data in statestorage 

Stack Trace:

Attaching the server log.
[vissv2MultipleSubscribe.LOG](https://github.com/w3c/automotive-viss2/files/13177062/vissv2MultipleSubscribe.LOG)

**Comment by UlfBj** [comment]
Fixed in PR#69
