### ISSUE TITLE
Ideas for leveraging Subscribe API against AAOS subscribable Vehicle Properties

### ISSUE THREAD

**Issue by volvorenjithraj** [w3c/automotive-viss2#73]
**Problem statement**
Android Automotive VHAL(single or muliple process) shall use VISSv2 gRPC Subscribe APIs to feed AAOS subscribable Vehicle Properties defined as part of Android Automotive standard Car APIs
https://developer.android.com/reference/android/car/VehiclePropertyIds

As per VISSv2 Subscribe API definition, accommodating  multiple signal request within a Subscribe is possible(https://www.w3.org/TR/viss2-core/#multiple-signals-request)
 _**When the request addresses multiple signals, the triggering condition shall only be evaluated on one of the signals, which is the first signal in the parameter array of paths. The first path in the array must therefore not contain wildcards to address multiple signals**_

As per above statement,process that expects multiple signal updates will not be able to use above API due to following issue

- Triggering condition is always based on first signal. If this condition never met, then other signal updates are not send back to client ?
- Branch/Domain(*) based Subscribe not possible since first path shall be valid path without wildcard characters

Viable Solution with current design is to have 'N' threads leveraging 'N' signals Subscribes which seems very inefficient. Please share thoughts and suggestions for such scenario

**Comment by slawr** [comment]
The inherent challenge of the limitation description aside (which is surprising) one solution could be in the internal changes to the reference implementation planned by the [COVESA Data Architecture group ](https://wiki.covesa.global/x/FoDHAg?src=sidebar) as part of the [Central Data Service Playground project](https://wiki.covesa.global/display/WIK4/Central+Data+Service+Playground).

We intend to add two new highly functional embedded database backends to WAII in the form of Apache IoTDB and MongoDB Realm. A more functional datastore will open up a range of timeseries data processing options. One of which would be access to more functional trigger mechanisms, e.g. for [Apache](https://iotdb.apache.org/UserGuide/V1.2.x/User-Manual/Database-Programming.html), which could be used to implement this.

**Comment by volvorenjithraj** [comment]
@slawr  Thank you for update. Did I understand correctly that consumer facing VISS APIs will be updated accordingly with back-end DB updates in future?  Probably an overhaul would be good considering the future on-board & off-board use cases as well.

**Comment by slawr** [comment]
Hi, Ultimately that comes down to discussion in the community.

I would say the Central Data Service Playground is intended to investigate such use cases. Please read the project page for the details and the Proposal in particular as it will be much clearer. The first instance of the Playground is expected to use WAII as the VISS Protocol Server to which we will add further DB back-ends as I mentioned. That will open up possibilities in various directions. 

One would be as you mention consistency of on-board and off-board uses cases in a data-centric architecture.

Another would be the connection between VISS and DB backends, both what it might mean for the protocol, but also improvements to the reference implementation. Things along the lines of your Android problem.

One nice aspect of the pattern of having feeders write to the store is the flexibility it opens up northbound.

To come back to your question, at the moment we are concentrating on implementing the playground. We are only just getting going but the major components are available so we expect to make good progress. Adding the new DB backends should be relatively straight forward. This is a community project in COVESA so it is difficult to provide specific release dates. Deliverables are driven by contributed effort. You can follow progress on Github and the COVESA wiki. Once the initial playground is available then we could discuss with the WAII community upstreaming the new DB backends and the community can use it to investigate issues like the one you describe.

I just wanted to make you aware of the project as the new functionality is one possible solution to the problem.

**Comment by slawr** [comment]
btw in case you are not aware of it, as you are working with Android you may find this COVESA project to standardise the needs for AOSP Apps interesting: https://wiki.covesa.global/display/WIK4/Automotive+AOSP+App+Framework+Standardization+Expert+Group

**Comment by UlfBj** [comment]
The thinking behind the triggering restriction I believe comes from that a request addressing multiple signals must not necessarily have the same datatype. As it is only possible to have one triggering condition in the request, applying that to signals of different datatypes seems problematic. 
The creator of the request have the freedom to choose which signal that is designated as "trigger signal".
But maybe this is too inflexible?
What would be an alternative design of this?
Bear in mind that this "problem" is only applicable to range/change trigger conditions.

**Comment by volvorenjithraj** [comment]
> The thinking behind the triggering restriction I believe comes from that a request addressing multiple signals must not necessarily have the same datatype. As it is only possible to have one triggering condition in the request, applying that to signals of different datatypes seems problematic. The creator of the request have the freedom to choose which signal that is designated as "trigger signal". But maybe this is too inflexible? What would be an alternative design of this? Bear in mind that this "problem" is only applicable to range/change trigger conditions.

Could there be a simple filter option for client ? Client could simply request for list of signal updates it requires & server shall return signal updates based on frequency it is placed on vehicle bus  ? For now I could keep speed as initial signal & followed by rest other interested signals. In this case client shall do this extra overhead of compare value/ignore or accept mechanism for rest of signals on every speed dispatch

**Comment by UlfBj** [comment]
@volvorenjithraj 
I am not so fond the idea of introducing new complexity to the VISSv2 spec (and thus server) at this point. 
I will bring it up in the next W3C WG meeting to hear the group's view on it.
I have not understood the current solution to be an absolute blocker to the use case you are referring to?

**Comment by slawr** [comment]
> 
> Yes, Have been following that group & but topic of 'standardization' of southbound interface of AAOS/VHAL towards HPC or ZC are not discussed as those are more part of framework but more platform level. I see more discussions on other project tracks though. We had a gRPC framework(Android VHAL <->VSS over gRPC <--> HPC/ZC) that already being used as this soundbound interface but it's server side is more proprietary of start up and falls into fragmented section. Our idea was to use same gRPC framework, but use VISS API & dockerized VISS server( Android VHAL <--> VSS over gRPC/VISSv2). This enables a platform/OEM agnostic interface which will work in both emulator & hardware.

Glad to hear you are aware and yes they don't appear to have this in their scope currently. You are maybe aware of this also but it was being looked at in the earlier [Android SiG](https://wiki.covesa.global/display/MIG/Android+Automotive+SIG+home). They considered both full data access via a server and greater app compatibility through mapping a smaller set to VHAL properties. There was work on the VHAL approach but it came to a stop when the companies behind it stepped away. I think it will come up again as its a needed component.

Thanks for the outline of what you are doing.

**Comment by volvorenjithraj** [comment]
Hope this will be addressed for future versions. Closing this as it is not a blocker & continuing with workaround
