### ISSUE TITLE
Docker compose fails due to missing directory /tmp/docker

### ISSUE THREAD

**Issue by slawr** [w3c/automotive-viss2#99]
**Summary**
The docker compose will fail as it references the directory /tmp/docker but this is not created by the Dockerfile or compose, nor is mitigated as a build setup requirement in the documentation in the docker readme or tutorial.

**Workaround**
Manually create the directory before building

**Comment by petervolvowinz** [comment]
The tmp/docker is setup so that we are able to use unix sockets thru a file share.  See: https://medium.com/@jonbaldie/how-to-connect-to-redis-with-unix-sockets-in-docker-9e94e01b7acd

**Comment by slawr** [comment]
Thanks for providing the background Peter.

**Comment by UlfBj** [comment]
Should be fixed by PR#119
